### ISSUE TITLE
What would happen when there is not enough space left on the server?

### ISSUE THREAD

**Issue by winjeg** [facebookincubator/OnlineSchemaChange#16]
will it crash ?
can it continue when we extend the disk space  ?

**Comment by cenalulu** [comment]
It will bail out once the remaining disk space is lower than the specified `--reserved-space` and exit with [`NOT_ENOUGH_SPACE `](https://github.com/facebookincubator/OnlineSchemaChange/blob/master/core/lib/error.py#L134-L138) error. 
OSC use trigger to record the DMLs that are happening on old table. If there isn't any space left, the triggers won't be able to record changes. Since it's not possible to put the trigger on hold, it makes `NOT_ENOUGH_SPACE` a critical and non-resumable error
